name: Regenerate the content-sitemap.xml

on:
  repository_dispatch:
    types:
      - resource-published
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: |
          echo "Status: ${{ github.event.client_payload.status }}"
          echo "Path: ${{ github.event.client_payload.path }}"
      - name: Configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        working-directory: ./tools/sitemap
        run: npm install
      - name: Run scripts and commit changes
        working-directory: ./tools/sitemap
        run: |
          node create.js
          git add ../../content-sitemap.xml
          git commit -m "Update generated content-sitemap.xml file"
          git push
