name: Regenerate the Coveo index XML
on:
  repository_dispatch:
    types:
      - resource-published
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Regenerate coveo.xml
        if: ${{ endsWith(github.event.client_payload.path, 'query-index.json') }}
        uses: actions/checkout@v3
        uses: actions/setup-node@v3
        with:
          node-version: '18'
        working-directory: ./coveo
        run: |
          node generate-coveo-sitemap.js
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./coveo-xml.xml
          git commit -m "Update generated coveo.xml file"
          git push
